<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>HTML (Selleck)</string>
    <key>comment</key>
    <string>Syntax file for Selleck templates containing HTML with Handlebars/Mustache placeholders.</string>
    <key>scopeName</key>
    <string>text.html.mustache.selleck</string>
    <key>fileTypes</key>
    <array>
        <string>handlebars</string>
        <string>hbs</string>
        <string>mustache</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x)
        (&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
        |&lt;!--(?!.*--&gt;)
        |\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
        |^[^\S\n]*(```)[^\S\n]*(.+?)?$
        )</string>
    <key>foldingStopMarker</key>
    <string>(?x)
        (&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
        |^\s*--&gt;
        |(^|\s)\}
        |^[^\S\n]*(```)[^\S\n]*$
        )</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#block</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#inline</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#mustache</string>
        </dict>
        <dict>
            <key>include</key>
            <string>text.html.basic</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>block</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#code-block</string>
                </dict>
            </array>
        </dict>
        <key>code-block</key>
        <dict>
            <key>begin</key>
            <string>^[^\S\n]*(```)[^\S\n]*(.+?)?$</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.code.selleck</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.code.selleck</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^[^\S\n]*(```)[^\S\n]*$</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.code.selleck</string>
                </dict>
            </dict>
            <key>name</key>
            <string>markup.raw.block.selleck</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#mustache</string>
                </dict>
            </array>
        </dict>
        <key>code-inline</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.code.selleck</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.code.selleck</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(`)(.+?)(`)</string>
            <key>name</key>
            <string>markup.raw.inline.selleck</string>
        </dict>
        <key>inline</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#code-inline</string>
                </dict>
            </array>
        </dict>
        <key>mustache</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>\{\{!</string>
                    <key>end</key>
                    <string>\}\}</string>
                    <key>name</key>
                    <string>comment.block.mustache</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\{\{[{&lt;&gt;#/]?</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.mustache</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\}?\}\}</string>
                    <key>name</key>
                    <string>source.mustache.embedded.html</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>uuid</key>
    <string>2E6E843B-13D3-4B1E-A889-0581D77BC7A2</string>
</dict>
</plist>
